name: Deploy Frontend
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag betb9/docker-react
    - name: Run tests
      run: docker run -e CI=true betb9/docker-react npm test -- --coverage
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*"
    - name: Deploy to ElasticBeanStalk
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        application_name: frontend
        environment_name: Frontend-env
        existing_bucket_name: elasticbeanstalk-eu-west-3-244928502257
        region: "eu-west-3"
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
