name: Deploy Frontend
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag betb9/docker-react:$(date +%s)
    - name: Run tests
      run: docker run -e CI=true betb9/docker-react:$(date +%s) npm test
